-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO JOIN ITEM_TREE USING (ITEM_ID)
WHERE ITEM_ID not in (SELECT distinct PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID is not null)
order by item_id desc