-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(USER_ID)) AS USERS
FROM USER_INFO JOIN ONLINE_SALE USING (USER_ID)
GROUP BY YEAR,MONTH, GENDER HAVING GENDER IS NOT NULL
ORDER BY 1,2,3;