-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, sum(PRICE*AMOUNT)AS TOTAL_SALES
FROM FOOD_PRODUCT JOIN FOOD_ORDER USING (PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY 3 desc, 1 asc