-- 코드를 입력하세요
SELECT HISTORY_ID, ROUND(A.DAILY_FEE*(DATEDIFF(B.END_DATE,B.START_DATE)+1)*
                         (1- CASE WHEN DISCOUNT_RATE IS NULL THEN 0 ELSE DISCOUNT_RATE END/100   )) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
LEFT
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE
AND CASE WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 >=30 THEN '30일 이상'
         WHEN DATEDIFF(B.END_DATE,B.START_DATE)+1 >=7 THEN '7일 이상'
         END = C.DURATION_TYPE
WHERE A.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;