-- 코드를 입력하세요
SELECT  a.TITLE, a.BOARD_ID,b.REPLY_ID, b.WRITER_ID,b.CONTENTS,date_format(b.CREATED_DATE,"%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_BOARD as a, USED_GOODS_REPLY as b
WHERE a.BOARD_ID = b.BOARD_ID and date_format(a.CREATED_DATE,"%Y%m")=202210
ORDER BY b.CREATED_DATE, a.TITLE